api_version = "2023-07"

[[extensions]]
name = "t:name"
handle = "Warpify"
type = "ui_extension"


# Both extension points are required
[[extensions.targeting]]
module = "./src/ProductIndexWarpifyExtension.tsx"
# The target used here must match the target used in the module file (./src/ProductDetailsConfigurationExtension.tsx)
target = "admin.product-index.selection-action.render"


[[extensions.targeting]]
module = "./src/ProductVariantDetailsConfigurationExtension.tsx"
# The target used here must match the target used in the module file (./src/ProductVariantDetailsConfigurationExtension.tsx)
target = "admin.product-details.action.render"
