api_version = "2024-04"

[[extensions]]
name = "Post on Warpcast"
handle = "Warpify"
type = "ui_extension"

[extensions.capabilities]
network_access = true

[[extensions.targeting]]
module = "./src/ProductVariantDetailsConfigurationExtension.tsx"
# The target used here must match the target used in the module file (./src/ProductVariantDetailsConfigurationExtension.tsx)
target = "admin.product-details.action.render"
